import { Instrument_Serif, Inter, } from "next/font/google";
import "./globals.css";

const InstrumentSerif = Instrument_Serif({
  weight: "400",
  variable: "--Instrument-Serif",
  subsets: ["latin"],
})

const InterFont = Inter({
  weight: "400",
  variable: "--Inter",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${InstrumentSerif.variable} ${InterFont.variable}`}>
      <body className="m-0">
        {children}
      </body>
    </html>
  );
}
